# Generated by Django 2.2.5 on 2020-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200713_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetstatement',
            name='price',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='price',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=14, null=True),
        ),
    ]
